name: mhs-ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-mhs-pretty:
    runs-on: ubuntu-latest
    steps:

    - name: checkout mhs repo
      uses: actions/checkout@v6
      with:
        repository: augustss/MicroHs
        ref: v0.14.23.1
        path: mhs
    - name: make and install mhs
      run: |
        cd mhs
        make minstall

    - name: checkout unordered-containers repo
      uses: actions/checkout@v6
      with:
        path: unordered-containers
    - name: compile and install unordered-containers package
      run: |
        PATH="$HOME/.mcabal/bin:$PATH"
        cd unordered-containers
        mcabal -r install

    - name: cleanup
      run: |
        rm -rf $HOME/.mcabal
